"use client";
import {useEffect,useState} from "react";
import {moduleApi} from "@/features/shared/module-api";
import {Panel,Field,inputClass,primaryClass,buttonClass,formData} from "@/features/shared/module-ui";
type Row={id:string;version:string;name?:string;title?:string;status?:string;kind?:string;priority?:string;message?:string;isRead?:boolean};
type Action={label:string;path:string;fields:string[];permission:string};
const engagement:Action[]=[{label:"Create group or committee",path:"communities",fields:["name","kind=group|committee","purpose"],permission:"engagement.manage"},{label:"Add community member",path:"communities/{communityId}/members",fields:["communityId","contactId","role"],permission:"engagement.manage"},{label:"Schedule meeting",path:"communities/{communityId}/meetings",fields:["communityId","subject","agenda","startsAtUtc:date"],permission:"engagement.manage"},{label:"Create campaign",path:"campaigns",fields:["communityId","name","subject"],permission:"engagement.manage"},{label:"Create fund",path:"funds",fields:["name","currency=GBP|EUR|USD","target:number"],permission:"engagement.manage"},{label:"Record contribution",path:"funds/{fundId}/contributions",fields:["fundId","contactId","kind=donation|pledge","amount:number","reference"],permission:"engagement.fundraise"}];
const work:Action[]=[{label:"Create task",path:"items",fields:["title","description","status=open|in-progress|done|cancelled","priority=normal|low|high","dueAtUtc:optionaldate","assigneeUserId:optional","teamId:optional","contactId:optional"],permission:"work.manage"}];
export function OperationsWorkspace({module,permissions}:{module:"engagement"|"work";permissions:string[]}){
 const [lists,setLists]=useState<Record<string,Row[]>>({}),[error,setError]=useState(""),[busy,setBusy]=useState(false),[detail,setDetail]=useState<unknown>(null),[notice,setNotice]=useState(""),[contacts,setContacts]=useState<Row[]>([]),[directory,setDirectory]=useState<{users:Row[];teams:Row[]}>({users:[],teams:[]});
 const sections=module==="engagement"?["communities","campaigns","funds"]:["items","notifications","imports"];
 async function load(){const names=module==="engagement"?["communities","campaigns","funds"]:["items","notifications","imports"];const values=await Promise.all(names.map(n=>moduleApi<Row[]>(module,"/"+n)));setLists(Object.fromEntries(names.map((n,i)=>[n,values[i]])));}
 useEffect(()=>{let active=true;const names=module==="engagement"?["communities","campaigns","funds"]:["items","notifications","imports"];Promise.all(names.map(n=>moduleApi<Row[]>(module,"/"+n))).then(values=>{if(active)setLists(Object.fromEntries(names.map((n,i)=>[n,values[i]])));}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[module]);
 async function run(action:()=>Promise<unknown>){setBusy(true);setError("");try{const value=await action();setDetail(value??null);await load();setNotice("Completed successfully.");}catch(e){setError(e instanceof Error?e.message:"Request failed");}finally{setBusy(false);}}
 return <main className="space-y-6 p-6"><h1 className="text-3xl font-semibold">{module==="engagement"?"Engagement and fundraising":"Tasks and notifications"}</h1><p className="text-slate-600">{module==="engagement"?"Manage communities, prepare consented campaign audiences, and record contributions. Campaign delivery and payment collection are not connected.":"Assign tasks, track progress, and validate imports before creating records."}</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<p role="status">{busy?"Working…":notice}</p>
 <Panel title="Contact directory"><form onSubmit={e=>{const d=formData(e);void run(async()=>{const results=await moduleApi<Row[]>(module,"/contacts?search="+encodeURIComponent(d.search));setContacts(results);return results;});}}><Field label="Find Contact"><input name="search" className={inputClass}/></Field><button className={buttonClass} disabled={busy}>Search contacts</button></form>{module==="work"&&<button className={buttonClass} onClick={()=>void run(async()=>{const results=await moduleApi<{users:Row[];teams:Row[]}>(module,"/directory");setDirectory(results);return results;})}>Show assignees and teams</button>}<p className="text-sm text-slate-500">Search contacts to populate the forms below.</p></Panel>
 <div className="grid gap-5 lg:grid-cols-2">{(module==="engagement"?engagement:work).filter(a=>permissions.includes(a.permission)).map(a=><Panel key={a.path} title={a.label}><form className="space-y-3" onSubmit={e=>{const d=formData(e);const body:Record<string,unknown>={};let path=a.path;for(const spec of a.fields){const [key]=spec.split("=");const [name,type]=key.split(":");body[name]=type==="number"?Number(d[name]):type?.includes("date")?(d[name]?new Date(d[name]).toISOString():null):d[name]||null;path=path.replace("{"+name+"}",encodeURIComponent(d[name]));}void run(()=>moduleApi(module,"/"+path,"POST",body));}}>{a.fields.map(spec=>{const [key,options]=spec.split("=");const [name,type]=key.split(":");const choices=name==="contactId"?contacts:name==="communityId"?(lists.communities??[]):name==="fundId"?(lists.funds??[]):name==="assigneeUserId"?directory.users:name==="teamId"?directory.teams:undefined;return <Field key={name} label={name.replace(/Id$/," ").replace(/([A-Z])/g," $1")}>{choices?<select name={name} required={!type?.startsWith("optional")} className={inputClass}><option value="">Choose {name.replace(/Id$/,"")}</option>{choices.map(c=><option key={c.id} value={c.id}>{c.name??c.title}</option>)}</select>:options?<select name={name} className={inputClass}>{options.split("|").map(v=><option key={v}>{v}</option>)}</select>:<input name={name} required={!type?.startsWith("optional")} type={type==="number"?"number":type?.includes("date")?"datetime-local":"text"} step={type==="number"?"0.01":undefined} className={inputClass}/>}</Field>})}<button disabled={busy} className={primaryClass}>{a.label}</button></form></Panel>)}</div>
 {sections.map(section=><Panel key={section} title={section}><ul className="space-y-3">{(lists[section]??[]).map(row=><li key={row.id} className="rounded border p-3"><strong>{row.name??row.title??row.message}</strong> <span>{row.status??row.kind??row.priority}</span><div className="mt-2 flex flex-wrap gap-2">{!["items","notifications","campaigns"].includes(section)&&<button className={buttonClass} onClick={()=>void run(()=>moduleApi(module,`/${section}/${row.id}`))}>View details</button>}{section==="campaigns"&&<><button className={buttonClass} onClick={()=>void run(()=>moduleApi(module,`/campaigns/${row.id}/audience`))}>View audience</button>{row.status==="draft"&&permissions.includes("engagement.manage")&&<button disabled={busy} className={buttonClass} onClick={()=>void run(()=>moduleApi(module,`/campaigns/${row.id}/prepare`,"POST",{version:row.version}))}>Prepare consented audience</button>}</>}{section==="notifications"&&!row.isRead&&<button disabled={busy} className={buttonClass} onClick={()=>void run(()=>moduleApi(module,`/notifications/${row.id}/read`,"POST"))}>Mark read</button>}{section==="items"&&permissions.includes("work.manage")&&<button disabled={busy||row.status==="done"} className={buttonClass} onClick={()=>void run(()=>moduleApi(module,`/items/${row.id}`,"PATCH",{...row,status:"done"}))}>Complete task</button>}{section==="imports"&&row.status==="preview"&&permissions.includes("work.import")&&permissions.includes("work.manage")&&<button disabled={busy} className={buttonClass} onClick={()=>void run(()=>moduleApi(module,`/imports/${row.id}/commit`,"POST",{version:row.version}))}>Commit validated import</button>}</div></li>)}</ul>{!lists[section]?.length&&<p>No records yet.</p>}</Panel>)}
 {module==="work"&&permissions.includes("work.import")&&<Panel title="Preview task import"><p>Paste up to 500 task rows as a JSON array. Each row needs title and priority (low, normal, high); dueAtUtc is optional.</p><form className="space-y-3" onSubmit={e=>{const d=formData(e);void run(()=>moduleApi(module,"/imports/preview","POST",{name:d.name,rows:JSON.parse(d.rows)}));}}><Field label="Import name"><input name="name" required className={inputClass}/></Field><Field label="Task rows"><textarea name="rows" required className={inputClass} defaultValue={'[{"title":"Follow up","priority":"normal"}]'}/></Field><button disabled={busy} className={primaryClass}>Validate and preview</button></form></Panel>}
 {module==="work"&&permissions.includes("work.export")&&<a href="/api/v1/work/export" download="nexora-tasks.csv" className={buttonClass}>Export tasks</a>}
 {detail!==null&&<Panel title="Results"><Result value={detail}/></Panel>}</main>;
}

function Result({value}:{value:unknown}){if(value===null||value===undefined)return null;if(Array.isArray(value))return <ul className="space-y-3">{value.map((item,i)=><li className="rounded border p-3" key={i}><Result value={item}/></li>)}</ul>;if(typeof value==="object")return <dl className="space-y-2">{Object.entries(value).filter(([key])=>!key.endsWith("Id")&&!["id","version","tenantId","correlationId"].includes(key)).map(([key,item])=><div key={key}><dt className="text-sm font-medium text-slate-500">{key.replace(/([A-Z])/g," $1")}</dt><dd><Result value={item}/></dd></div>)}</dl>;return <span>{String(value)}</span>;}
