"use client";
import { useEffect, useState } from "react";
import { moduleApi } from "../shared/module-api";
import { Field, Panel, formData, inputClass as input, buttonClass as button, primaryClass as primary } from "../shared/module-ui";
type Product = { id:string; name:string; category:string; termMonths:number; rate:number; currency:string; isActive:boolean; version:string };
type Application = { id:string; contactName:string; productId:string; status:string; version:string; quotedRate:number; currency:string; requestedStartUtc:string };
type Member = { id:string; contactName:string; productId:string; status:string; startsAtUtc:string; endsAtUtc:string; rate:number; currency:string; version:string };
type History = { id:string; action:string; reason:string; createdAtUtc:string };
type Contact = { id:string; name:string };
const api = <T,>(path:string,method="GET",body?:unknown) => moduleApi<T>("membership",path,method,body);
export function MembershipWorkspace({ permissions }: { permissions:string[] }) {
 const [products,setProducts]=useState<Product[]>([]); const [applications,setApplications]=useState<Application[]>([]); const [members,setMembers]=useState<Member[]>([]); const [contacts,setContacts]=useState<Contact[]>([]);
 const [refresh,setRefresh]=useState(0); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true);
 const [selected,setSelected]=useState<Member|null>(null); const [history,setHistory]=useState<History[]>([]); const [editing,setEditing]=useState<Product|null>(null); const [tab,setTab]=useState("members");
 const manage=permissions.includes("membership.manage"); const decide=permissions.includes("membership.decide");
 useEffect(()=>{ let active=true; Promise.all([api<Product[]>("/products"),api<Application[]>("/applications"),api<Member[]>("/members"),api<Contact[]>("/contacts")]).then(([p,a,m,c])=>{if(active){setProducts(p);setApplications(a);setMembers(m);setContacts(c);setLoading(false);}}).catch(e=>{if(active){setError(e.message);setLoading(false);}});return()=>{active=false;};},[refresh]);
 async function perform(action:()=>Promise<void>,reload=true){setBusy(true);setError("");try{await action();if(reload)setRefresh(v=>v+1);}catch(e){setError(e instanceof Error?e.message:"Unable to save.");}finally{setBusy(false);}}
 async function open(id:string){await perform(async()=>{const result=await api<{member:Member;history:History[]}>(`/members/${id}`);setSelected(result.member);setHistory(result.history);},false);}
 return <main className="mx-auto max-w-7xl space-y-5 p-4 text-slate-800 sm:p-7"><header><p className="text-xs font-semibold uppercase tracking-widest text-indigo-600">Member services</p><h1 className="mt-1 text-3xl font-semibold">Membership</h1><p className="mt-2 text-sm text-slate-600">Applications, decisions and the complete membership lifecycle.</p></header>
 {error&&<div role="alert" className="rounded-lg bg-red-50 p-4 text-sm text-red-800">{error} <button className={button} onClick={()=>{setError("");setRefresh(v=>v+1);}}>Reload</button></div>}
 <nav aria-label="Membership sections" className="flex flex-wrap gap-2">{["members","applications","products"].map(t=><button key={t} className={tab===t?primary:button} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</nav>
 {loading&&<p role="status">Loading membership…</p>}
 {tab==="products"&&<><Panel title="Products and rates"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Membership products</caption><thead><tr>{["Product","Category","Term","Rate","State","Action"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{products.map(p=><tr key={p.id} className="border-t border-slate-200"><td className="p-3">{p.name}</td><td className="p-3">{p.category}</td><td className="p-3">{p.termMonths} months</td><td className="p-3">{p.currency} {p.rate.toFixed(2)}</td><td className="p-3">{p.isActive?"Available":"Inactive"}</td><td className="p-3">{manage&&<button className={button} onClick={()=>setEditing(p)}>Edit {p.name}</button>}</td></tr>)}</tbody></table></div>{products.length===0&&<p className="py-5 text-sm">Create a product to start accepting applications.</p>}</Panel>
 {manage&&<Panel title={editing?"Edit product":"Create product"}><form key={editing?.version??"new"} className="grid gap-3 sm:grid-cols-3" onSubmit={e=>{const r=formData(e);const form=e.currentTarget;void perform(async()=>{await api(editing?`/products/${editing.id}`:"/products",editing?"PATCH":"POST",{...r,rate:Number(r.rate),termMonths:Number(r.termMonths),isActive:r.isActive==="true",version:editing?.version});setEditing(null);form.reset();});}}><Field label="Product name"><input name="name" className={input} maxLength={160} defaultValue={editing?.name} required/></Field><Field label="Category"><input name="category" className={input} maxLength={80} defaultValue={editing?.category} required/></Field><Field label="Term in months"><input name="termMonths" className={input} type="number" min={1} max={60} defaultValue={editing?.termMonths??12} required/></Field><Field label="Rate"><input name="rate" className={input} type="number" min={0} step="0.01" defaultValue={editing?.rate??0} required/></Field><Field label="Currency"><select name="currency" className={input} defaultValue={editing?.currency??"GBP"}>{["GBP","EUR","USD"].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Availability"><select name="isActive" className={input} defaultValue={String(editing?.isActive??true)}><option value="true">Available</option><option value="false">Inactive</option></select></Field><div className="flex gap-2"><button className={primary} disabled={busy}>Save product</button>{editing&&<button className={button} type="button" onClick={()=>setEditing(null)}>Cancel edit</button>}</div></form><p className="mt-3 text-xs text-slate-500">New rates apply to new applications and renewals. Existing application quotes are preserved.</p></Panel>}</>}
 {tab==="applications"&&<><Panel title="Applications"><ul className="space-y-4">{applications.map(a=><li key={a.id} className="rounded-lg border border-slate-200 p-4"><p className="font-medium">{a.contactName} · {products.find(p=>p.id===a.productId)?.name}</p><p className="my-2 text-sm">{a.status} · Quoted {a.currency} {a.quotedRate.toFixed(2)}</p>{decide&&a.status==="submitted"&&<form className="flex flex-wrap items-end gap-3" onSubmit={e=>{const r=formData(e);void perform(async()=>{await api(`/applications/${a.id}/decision`,"POST",{...r,version:a.version});});}}><Field label="Decision"><select name="decision" className={input}><option value="approve">Approve and activate</option><option value="reject">Reject</option></select></Field><Field label="Decision reason"><input name="reason" className={input} maxLength={500} required/></Field><button className={primary} disabled={busy}>Record decision</button></form>}</li>)}</ul>{applications.length===0&&<p className="text-sm">No applications yet.</p>}</Panel>{manage&&<Panel title="Submit application"><form className="mb-4 flex items-end gap-2" onSubmit={e=>{const r=formData(e);void perform(async()=>setContacts(await api<Contact[]>(`/contacts?search=${encodeURIComponent(r.search)}`)),false);}}><Field label="Find Contact"><input className={input} name="search" maxLength={160}/></Field><button className={button} disabled={busy}>Find</button></form><form className="grid items-end gap-3 sm:grid-cols-3" onSubmit={e=>{const r=formData(e);const form=e.currentTarget;void perform(async()=>{await api("/applications","POST",{...r,startsAtUtc:r.startsAtUtc+"T00:00:00Z"});form.reset();});}}><Field label="Contact"><select name="contactId" className={input} required><option value="">Choose Contact</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Product"><select name="productId" className={input} required><option value="">Choose product</option>{products.filter(p=>p.isActive).map(p=><option key={p.id} value={p.id}>{p.name} · {p.currency} {p.rate}</option>)}</select></Field><Field label="Start date"><input name="startsAtUtc" className={input} type="date" required/></Field><button className={primary} disabled={busy}>Submit application</button></form></Panel>}</>}
 {tab==="members"&&<><Panel title="Members"><form className="mb-4 flex flex-wrap items-end gap-3" onSubmit={e=>{const r=formData(e);void perform(async()=>setMembers(await api<Member[]>(`/members?search=${encodeURIComponent(r.search)}&status=${r.status}`)),false);}}><Field label="Search members"><input name="search" className={input}/></Field><Field label="Status"><select name="status" className={input}><option value="">All statuses</option>{["active","cancelled","lapsed"].map(s=><option key={s}>{s}</option>)}</select></Field><button className={button} disabled={busy}>Search</button></form><div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Member subscriptions</caption><thead><tr>{["Member","Product","Status","Term end","Rate"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{members.map(m=><tr key={m.id} className="border-t border-slate-200"><th className="p-3"><button className="font-medium text-indigo-700 underline" onClick={()=>void open(m.id)}>{m.contactName}</button></th><td className="p-3">{products.find(p=>p.id===m.productId)?.name}</td><td className="p-3">{m.status}</td><td className="p-3">{new Date(m.endsAtUtc).toLocaleDateString()}</td><td className="p-3">{m.currency} {m.rate.toFixed(2)}</td></tr>)}</tbody></table></div>{members.length===0&&<p className="py-5 text-sm">No matching memberships. Approve an application to activate one.</p>}</Panel>{selected&&<Panel title={selected.contactName}><p className="mb-3 text-sm">{selected.status} · {new Date(selected.startsAtUtc).toLocaleDateString()} to {new Date(selected.endsAtUtc).toLocaleDateString()}</p>{manage&&<form className="mb-5 flex flex-wrap items-end gap-3" onSubmit={e=>{const r=formData(e);void perform(async()=>{const m=await api<Member>(`/members/${selected.id}/${r.action}`,"POST",{version:selected.version,reason:r.reason});setSelected(m);setHistory((await api<{history:History[]}>(`/members/${m.id}`)).history);});}}><Field label="Membership action"><select name="action" className={input}>{selected.status==="cancelled"?<option value="reinstate">Reinstate</option>:<><option value="renew">Renew at current product rate</option>{selected.status==="active"&&<><option value="cancel">Cancel membership</option><option value="lapse">Mark expired membership lapsed</option></>}</>}</select></Field><Field label="Reason"><input name="reason" className={input} maxLength={500} required/></Field><button className={primary} disabled={busy}>Apply change</button></form>}<h3 className="mb-3 font-semibold">Status history</h3><ol className="space-y-3">{history.map(h=><li key={h.id} className="border-l-2 border-indigo-200 pl-3 text-sm"><strong>{h.action.replaceAll("."," ")}</strong><p>{h.reason}</p><time className="text-xs text-slate-500">{new Date(h.createdAtUtc).toLocaleString()}</time></li>)}</ol></Panel>}</>}
 </main>;
}
