"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Trash2 } from "lucide-react";
import { crm } from "@/features/crm/api";

export default function AttributesControllerPage({ params }: { params: Promise<{ module: string }> }) {
  const [module, setModule] = useState(""); const [attributes, setAttributes] = useState<string[]>([]); const [draft, setDraft] = useState(""); const [saved, setSaved] = useState(false);
  useEffect(() => { void params.then(async p => { setModule(p.module); if (p.module === "contacts" || p.module === "accounts") { const fields = await crm<{ name: string }[]>("/fields"); setAttributes(fields.map(f => f.name)); } }); }, [params]);
  if (!module) return null;
  const name = module.replaceAll("-", " ").replace(/\b\w/g, c => c.toUpperCase());
  return <main className="page-enter mx-auto max-w-3xl space-y-6 p-5 text-slate-800 sm:p-8"><Link href={`/automations/${module}`} className="inline-flex items-center gap-2 text-sm font-medium text-indigo-700 hover:underline"><ArrowLeft className="size-4" />{name} automations</Link><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-indigo-600">Attributes controller</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Manage {name} attributes</h1><p className="mt-2 text-sm text-slate-600">Add new fields or remove existing attributes. Save to apply the configuration to entity forms.</p></header><form className="flex gap-2" onSubmit={e => { e.preventDefault(); if (draft.trim() && !attributes.includes(draft.trim())) { const next = [...attributes, draft.trim()]; setAttributes(next); localStorage.setItem(`nexora-attributes-${module}`, JSON.stringify(next)); } setDraft(""); setSaved(false); }}><input className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm" value={draft} onChange={e => setDraft(e.target.value)} placeholder="New attribute name" required /><button className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Add attribute</button></form><ul className="divide-y rounded-xl border border-slate-200 bg-white">{attributes.map(attribute => <li key={attribute} className="flex items-center justify-between p-4 text-sm"><span>{attribute}</span><button type="button" className="text-rose-600" aria-label={`Remove ${attribute}`} onClick={() => { setAttributes(attributes.filter(x => x !== attribute)); localStorage.setItem(`nexora-attributes-${module}`, JSON.stringify(attributes.filter(x => x !== attribute))); setSaved(false); }}><Trash2 className="size-4" /></button></li>)}</ul><div className="flex justify-end gap-3"><span className="text-sm text-emerald-700">{saved ? "Changes saved" : ""}</span><button type="button" className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm" onClick={() => setAttributes(JSON.parse(localStorage.getItem(`nexora-attributes-${module}`) ?? "[]"))}>Cancel</button><button type="button" className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white" onClick={async () => { if (module === "contacts" || module === "accounts") { for (const attribute of attributes) { try { await crm("/fields", "POST", { name: attribute, kind: module === "contacts" ? "contact" : "account", dataType: "text" }); } catch {} } } localStorage.setItem(`nexora-attributes-${module}`, JSON.stringify(attributes)); setSaved(true); }}>Save changes</button></div></main>;
}



