"use client";
import {useEffect,useState} from "react";
import {moduleApi} from "@/features/shared/module-api";
import {Panel,Field,inputClass,primaryClass,buttonClass,formData} from "@/features/shared/module-ui";
type Dataset={key:string;title:string;count:number};type Row={id:string;label:string;status:string;createdAtUtc:string};
export function InsightsWorkspace({canExport}:{canExport:boolean}){
 const [datasets,setDatasets]=useState<Dataset[]>([]),[key,setKey]=useState(""),[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[error,setError]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState({search:"",status:"",fromUtc:null as string|null,toUtc:null as string|null,skip:0,take:50});
 useEffect(()=>{moduleApi<{datasets:Dataset[]}>("insights","/dashboard").then(d=>{setDatasets(d.datasets);setKey(d.datasets[0]?.key??"");}).catch(e=>setError(e.message));},[]);
 async function run(q:typeof query){setBusy(true);setError("");try{const page=await moduleApi<{items:Row[];total:number}>("insights","/query/"+key,"POST",q);setRows(page.items);setTotal(page.total);setQuery(q);}catch(e){setError(e instanceof Error?e.message:"Report failed");}finally{setBusy(false);}}
 async function exportReport(){setBusy(true);setError("");try{const csrf=await fetch("/api/v1/auth/csrf",{cache:"no-store"});if(!csrf.ok)throw new Error("Sign in again.");const {token}=await csrf.json();const response=await fetch("/api/v1/insights/export/"+key,{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-TOKEN":token},body:JSON.stringify(query)});if(!response.ok){const p=await response.json();throw new Error(p.errors?Object.values(p.errors).flat().join(" "):p.title??"Export failed.");}const url=URL.createObjectURL(await response.blob());const a=document.createElement("a");a.href=url;a.download="nexora-"+key+".csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:"Export failed");}finally{setBusy(false);}}
 return <main className="space-y-6 p-6"><h1 className="text-3xl font-semibold">Insights</h1><p className="text-slate-600">Explore records available to your tenant and role. Counts reflect the time this page loaded.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="grid gap-4 sm:grid-cols-3">{datasets.map(d=><Panel key={d.key} title={d.title}><p className="text-3xl font-semibold">{d.count}</p></Panel>)}</div><Panel title="Build a report"><form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>{const d=formData(e);void run({search:d.search,status:d.status,fromUtc:d.from?new Date(d.from).toISOString():null,toUtc:d.to?new Date(d.to).toISOString():null,skip:0,take:50});}}><Field label="Dataset"><select className={inputClass} value={key} onChange={e=>{setKey(e.target.value);setRows([]);setTotal(0);}}>{datasets.map(d=><option key={d.key} value={d.key}>{d.title}</option>)}</select></Field><Field label="Name contains"><input name="search" maxLength={160} className={inputClass}/></Field><Field label="Exact status"><input name="status" maxLength={80} className={inputClass}/></Field><Field label="Created on or after"><input name="from" type="date" className={inputClass}/></Field><Field label="Created before"><input name="to" type="date" className={inputClass}/></Field><button disabled={busy||!key} className={primaryClass}>Run report</button></form></Panel><Panel title="Report results"><p role="status">{busy?"Loading…":`${total} matching records`}</p><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Name</th><th>Status</th><th>Created</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.label}</td><td>{r.status}</td><td>{new Date(r.createdAtUtc).toLocaleDateString()}</td></tr>)}</tbody></table></div><div className="mt-4 flex gap-3"><button disabled={busy||query.skip===0} className={buttonClass} onClick={()=>void run({...query,skip:Math.max(0,query.skip-50)})}>Previous</button><button disabled={busy||query.skip+50>=total} className={buttonClass} onClick={()=>void run({...query,skip:query.skip+50})}>Next</button>{canExport&&<button disabled={busy||!key} className={buttonClass} onClick={()=>void exportReport()}>Export matching records</button>}</div></Panel></main>;
}
