"use client";
import { AttributeFields } from "../shared/attribute-fields";
import { RecordAttributes } from "../shared/record-attributes";
import { useEffect,useState } from "react";
import { moduleApi } from "../shared/module-api";
import { Field,Panel,formData,inputClass as input,buttonClass as button,primaryClass as primary } from "../shared/module-ui";
type Offering={id:string;kind:string;name:string;venue:string;startsAtUtc:string;endsAtUtc:string;capacity:number;status:string;version:string};
type Enrollment={id:string;contactName:string;status:string;version:string};
type Detail={offering:Offering;sessions:{id:string;name:string;startsAtUtc:string;endsAtUtc:string}[];enrollments:Enrollment[];results:{id:string;enrollmentId:string;score:number;outcome:string}[];history:{id:string;action:string;reason:string;createdAtUtc:string}[]};
const api=<T,>(p:string,m="GET",b?:unknown)=>moduleApi<T>("events",p,m,b);
export function EventsWorkspace({permissions}:{permissions:string[]}){
 const [offerings,setOfferings]=useState<Offering[]>([]);const [detail,setDetail]=useState<Detail|null>(null);const [contacts,setContacts]=useState<{id:string;name:string}[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [refresh,setRefresh]=useState(0);const [kind,setKind]=useState("");
 const manage=permissions.includes("events.manage");const results=permissions.includes("events.results");
 useEffect(()=>{let active=true;Promise.all([api<Offering[]>("/offerings"),api<{id:string;name:string}[]>("/contacts")]).then(([o,c])=>{if(active){setOfferings(o);setContacts(c);setLoading(false);}}).catch(e=>{if(active){setError(e.message);setLoading(false);}});return()=>{active=false;};},[refresh]);
 async function perform(action:()=>Promise<void>,reload=true){setBusy(true);setError("");try{await action();if(reload)setRefresh(v=>v+1);}catch(e){setError(e instanceof Error?e.message:"Unable to save.");}finally{setBusy(false);}}
 async function reloadDetail(id:string){setDetail(await api<Detail>(`/offerings/${id}`));}
 return <main className="mx-auto max-w-7xl space-y-5 p-4 text-slate-800 sm:p-7"><header><p className="text-xs font-semibold uppercase tracking-widest text-indigo-600">Programmes and participation</p><h1 className="mt-1 text-3xl font-semibold">Events and learning</h1><p className="mt-2 text-sm text-slate-600">Events, training applications, exam bookings and results.</p></header>{error&&<div role="alert" className="rounded-lg bg-red-50 p-4 text-sm text-red-800">{error}<button className={button} onClick={()=>{setError("");setRefresh(v=>v+1);}}>Reload</button></div>}{loading&&<p role="status">Loading schedule…</p>}
 <Panel title="Schedule"><Field label="Type"><select className={input} value={kind} onChange={e=>setKind(e.target.value)}><option value="">All types</option>{["event","course","exam"].map(k=><option key={k}>{k}</option>)}</select></Field><ul className="mt-4 grid gap-3 md:grid-cols-2">{offerings.filter(o=>!kind||o.kind===kind).map(o=><li key={o.id} className="rounded-lg border border-slate-200 p-4"><button className="font-semibold text-indigo-700 underline" onClick={()=>void perform(()=>reloadDetail(o.id),false)}>{o.name}</button><p className="mt-2 text-sm">{o.kind} · {o.status} · {o.capacity} places</p><p className="text-sm">{new Date(o.startsAtUtc).toLocaleString()} · {o.venue}</p></li>)}</ul>{offerings.length===0&&<p className="mt-4 text-sm">Publish your first event, course or exam.</p>}</Panel>
 {manage&&<Panel title="Publish a schedule"><form className="grid gap-3 sm:grid-cols-3" onSubmit={e=>{const r=formData(e);const form=e.currentTarget;void perform(async()=>{const o=await api<Offering>("/offerings","POST",{...r,startsAtUtc:new Date(r.startsAtUtc).toISOString(),endsAtUtc:new Date(r.endsAtUtc).toISOString(),capacity:Number(r.capacity),passingScore:Number(r.passingScore)});form.reset();await reloadDetail(o.id);});}}><Field label="Name"><input className={input} name="name" maxLength={160} required/></Field><Field label="Type"><select className={input} name="kind">{["event","course","exam"].map(k=><option key={k}>{k}</option>)}</select></Field><Field label="Venue or online location"><input className={input} name="venue" maxLength={160} required/></Field><Field label="Starts"><input className={input} name="startsAtUtc" type="datetime-local" required/></Field><Field label="Ends"><input className={input} name="endsAtUtc" type="datetime-local" required/></Field><Field label="Capacity"><input className={input} name="capacity" type="number" min={1} max={100000} defaultValue={30} required/></Field><Field label="Exam passing score"><input className={input} name="passingScore" type="number" min={0} max={100} defaultValue={50} required/></Field><button className={primary} disabled={busy}>Publish</button><AttributeFields module="events" kind="Offering" /></form></Panel>}
 {detail&&<><Panel title={detail.offering.name}><p className="mb-4 text-sm">{detail.offering.status} · {detail.enrollments.filter(e=>["registered","attended"].includes(e.status)).length}/{detail.offering.capacity} places filled</p>{manage&&detail.offering.status==="published"&&<form className="mb-4 flex flex-wrap items-end gap-3" onSubmit={e=>{const r=formData(e);void perform(async()=>{await api(`/offerings/${detail.offering.id}/cancel`,"POST",{version:detail.offering.version,reason:r.reason});await reloadDetail(detail.offering.id);});}}><Field label="Reason to cancel offering and pending bookings"><input className={input} name="reason" maxLength={500} required/></Field><button className={button} disabled={busy}>Cancel offering</button></form>}<h3 className="font-semibold">Sessions</h3><ul className="my-3 space-y-2">{detail.sessions.map(s=><li key={s.id} className="text-sm">{s.name} · {new Date(s.startsAtUtc).toLocaleString()} – {new Date(s.endsAtUtc).toLocaleTimeString()}</li>)}</ul>{manage&&detail.offering.status==="published"&&<form className="grid items-end gap-3 sm:grid-cols-3" onSubmit={e=>{const r=formData(e);const form=e.currentTarget;void perform(async()=>{await api(`/offerings/${detail.offering.id}/sessions`,"POST",{...r,startsAtUtc:new Date(r.startsAtUtc).toISOString(),endsAtUtc:new Date(r.endsAtUtc).toISOString()});form.reset();await reloadDetail(detail.offering.id);});}}><Field label="Session name"><input className={input} name="name" required maxLength={160}/></Field><Field label="Session starts"><input className={input} name="startsAtUtc" type="datetime-local" required/></Field><Field label="Session ends"><input className={input} name="endsAtUtc" type="datetime-local" required/></Field><button className={button} disabled={busy}>Add session</button><AttributeFields module="events" kind="EventSession" /></form>}</Panel>
 <Panel title={detail.offering.kind==="course"?"Training applications and attendance":"Bookings and attendance"}>{manage&&detail.offering.status==="published"&&<><form className="mb-3 flex items-end gap-2" onSubmit={e=>{const r=formData(e);void perform(async()=>setContacts(await api(`/contacts?search=${encodeURIComponent(r.search)}`)),false);}}><Field label="Find Contact"><input className={input} name="search" maxLength={160}/></Field><button className={button}>Find</button></form><form className="mb-5 flex items-end gap-3" onSubmit={e=>{const r=formData(e);void perform(async()=>{await api(`/offerings/${detail.offering.id}/enrollments`,"POST",r);await reloadDetail(detail.offering.id);});}}><Field label="Participant"><select className={input} name="contactId" required><option value="">Choose Contact</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><button className={primary} disabled={busy}>{detail.offering.kind==="course"?"Apply for training":"Book place"}</button><AttributeFields module="events" kind="Enrollment" /></form></>}
 <ul className="space-y-4">{detail.enrollments.map(e=><li key={e.id} className="rounded-lg border border-slate-200 p-4"><p className="font-medium">{e.contactName} · {e.status}</p>{manage&&detail.offering.status==="published"&&["submitted","registered","waitlisted"].includes(e.status)&&<form className="mt-3 grid items-end gap-3 sm:grid-cols-4" onSubmit={event=>{const r=formData(event);void perform(async()=>{await api(`/enrollments/${e.id}/${r.action}`,"POST",{version:e.version,reason:r.reason,targetOfferingId:r.targetOfferingId||null});await reloadDetail(detail.offering.id);});}}><Field label="Booking action"><select className={input} name="action">{(e.status==="submitted"?["approve","reject","cancel"]:e.status==="waitlisted"?["promote","transfer","cancel"]:["attend","transfer","cancel"]).map(a=><option key={a}>{a}</option>)}</select></Field><Field label="Reason"><input className={input} name="reason" maxLength={500} required/></Field><Field label="Transfer destination"><select className={input} name="targetOfferingId"><option value="">Only for transfers</option>{offerings.filter(o=>o.id!==detail.offering.id&&o.kind===detail.offering.kind&&o.status==="published").map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field><button className={button} disabled={busy}>Apply action</button></form>}{results&&detail.offering.kind==="exam"&&e.status==="attended"&&!detail.results.some(r=>r.enrollmentId===e.id)&&<form className="mt-3 flex items-end gap-3" onSubmit={event=>{const r=formData(event);void perform(async()=>{await api(`/enrollments/${e.id}/result`,"POST",{...r,version:e.version,score:Number(r.score)});await reloadDetail(detail.offering.id);});}}><Field label="Exam score"><input className={input} name="score" type="number" min={0} max={100} required/></Field><button className={primary} disabled={busy}>Publish result</button><AttributeFields module="events" kind="ExamResult" /></form>}{detail.results.filter(r=>r.enrollmentId===e.id).map(r=><p key={r.id} className="mt-3 text-sm font-semibold">Result: {r.score}/100 · {r.outcome}</p>)}</li>)}</ul></Panel><Panel title="Activity"><ol className="space-y-3">{detail.history.map(h=><li key={h.id} className="border-l-2 border-indigo-200 pl-3 text-sm"><strong>{h.action.replaceAll("."," ")}</strong><p>{h.reason}</p><time>{new Date(h.createdAtUtc).toLocaleString()}</time></li>)}</ol></Panel></>}
 <RecordAttributes module="events" canEdit={permissions.includes("events.manage")} />
 </main>;
}
